### ISSUE TITLE
[bug]: if an output already spent error occurs, the client fails and cannot be turned on anymore

### ISSUE THREAD

**Issue by kulisekf** [lightninglabs/taproot-assets#406] opened 2023-07-17 21:30 UTC
tested on 2 setups:
1. Polar v2.0.0; Docker v20.10.21; Compose v2.13.0 (Win 10); network setup: 1 Bitcoin Core v25.0; 2 LND v0.16.2-beta; 2 Taproot Assets v0.2.0-alpha
2. Ubuntu 20.04; lncli version 0.16.3-beta; tapcli version 0.2.2-alpha

If the client reaches the state Error evaluating state (SendStateBroadcast): rpc error: code = Unknown desc = transaction rejected: output already spent, the client turns off and cannot be turned on again. When trying to power on again, the following occurs:
```
2023-07-17 23:02:15.888 [INF] RPCS: Starting RPC Server
2023-07-17 23:02:15.888 [INF] RPCS: RPC server listening on 127.0.0.1:10029
2023-07-17 23:02:15.888 [INF] CONF: Starting HTTPS REST proxy listener at 127.0.0.1:8089
2023-07-17 23:02:15.889 [INF] RPCS: gRPC proxy started at 127.0.0.1:8089
2023-07-17 23:02:15.889 [INF] SRVR: Taproot Asset Daemon fully active!
2023-07-17 23:02:15.889 [ERR] SRVR: Shutting down because error in main method: received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-07-17 23:02:15.889 [INF] RPCS: Stopping RPC Server
2023-07-17 23:02:15.889 [INF] SRVR: Shutdown complete
```

As part of polar, I got to this state by following the procedure reported in the error https://github.com/lightninglabs/taproot-assets/issues/405

On ubuntu, I managed to get to this state in another way, but I am currently unable to repeat it. However, within this error, the status is then the same, the tapd client cannot be turned on again with the same return

**Comment by guggero** [comment] 2023-07-18 08:35
For 0.2.0 on Polar that is kind of expected, as we explicitly fixed this with 0.2.2.
Are you sure on Ubuntu you got into the situation with 0.2.2 and not before updating to that version?
If yes, it would be really useful to know how exactly you got into that situation.

**Comment by kulisekf** [comment] 2023-07-18 09:30
@guggero I quickly 2x repeated the procedure on ubuntu, which I used to get to this state and the result is the same. Procedure (I have a newly initialized tapd client, before the beginning I deleted the .tapd folder and let the client recreate it -> tapd commands, ctrl+c after startup and then start with connection to lnd node):
1. Minted the asset: `tapcli assets mint --type normal --name fantasycoin_test --supply 100 --meta_bytes "fantastic money"`
2. Finalized `tapcli assets mint f` and waited for the transaction to be included in the block
3. Now generated 2 addresses with the same parameters for this asset with suply > 50%: tapcli addrs new --asset_id {asset_id} --amt 90
4. I sent to both of these addresses immediately after each other: `tapcli assets send --addr {addr-1}` `tapcli assets send --addr {addr-2}`
5. After sending the 2nd transaction, the client is either loopy, stuck or something similar - you need to turn off the process using ctrl+C. Regardless of whether or not I interrupt the sending process with ctrl+C, once the next block has been mined the client fails with the expected error and cannot be turned on anymore

**Comment by guggero** [comment] 2023-07-18 10:10
Ah okay, thanks for the repro.
This is kind of expected, since when you send out the first transaction, the Bitcoin UTXO that contains the assets is being spent and you need to wait for it to confirm before you can send the second transaction.
So you either need to do a multi-send (the RPC supports sending to multiple addresses at the same time, not sure if we added that to the command line as well).

Basically we need to implement https://github.com/lightninglabs/taproot-assets/issues/261 to give you a proper error message on the second send attempt (something along the lines of "no confirmed asset outputs available, please wait for previous sends to confirm before sending again").

So things should work as expected if you do `tapcli assets send ...`, wait for a block (or mine one if you're on regtest), then do the second send.

I'm going to close this as a duplicate of https://github.com/lightninglabs/taproot-assets/issues/261 (and also related to https://github.com/lightninglabs/taproot-assets/issues/374) for now.

**Closed by guggero** 2023-07-18 10:10 UTC
Labels: needs triage
