### ISSUE TITLE
Use `meta_data` field to covey an asset's `characteristic`

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#925] opened 2024-06-04 18:58 UTC
### Discussed in https://github.com/lightninglabs/taproot-assets/discussions/763

<div type='discussions-op-text'>

<sup>Originally posted by **dstadulis** January 10, 2024</sup>
### Background
Using integers in applications which require uncompromising accuracy (Money, accounting, settlement etc) is common in order to handle the onerous computer hardware and software demands to perform accurate operations on floating point numbers.  IEEE 754 is a standards example of the attempts to create uniformity in how to implement computation on floats.
Financial accounting software often uses integers to achieve accuracy without subjecting itself to FP arithmetic complexity.
https://en.wikipedia.org/wiki/IEEE_754
https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

tapd uses integers to ensure that it's precision and accuracy is high.  Bitcoin similarly uses integers for internal account and `COIN = 100000000` used to convert/present the decimal in the UI.

Such a variable merely instructs UIs on where to place the decimal point and referred to as a `characteristic`. [1]

### User / Market Needs
As a `application developer` I want an `programmatic, authenticated method to produce an asset's characteristic` in order to `make the presentation of tapd's internally-accounted integers be displayed in UIs without needing bespoke code`
As an `Asset Issuer` I want to `convey where the decimal place should be displayed to users` in order to `prevent confusion and calculation errors in handling amounts`

### Resources
[1] https://en.wikipedia.org/wiki/Characteristic_(exponent_notation)#Mantissa_and_characteristic
https://en.wikipedia.org/wiki/Significand</div>

**Comment by Roasbeef** [comment] 2024-06-04 18:59
Could also call it precision.

**Comment by Roasbeef** [comment] 2024-06-04 19:18
Current plan:
  * Add `precision` to the minting RPC. This is an integer, it's an integer in the JSON as well.
     * We'd also display this for any asset display call on RPC, including the Universe calls. 
     * Wallets are to use this to modify the way they display assets. Eg: if you have 1000 units on an asset, and the `precision` is set to 2, then it's displayed as `10.00` in UIs. 
     * This also has implications for the RFQ and channel layer as well. Ideally the smallest unit of the asset should be on par or less than the value of a satoshi, ideally a milli-satoshi. 
  * If this is set, then the meta type MUST be JSON, fail otherwise. 
  * If we have meta JSON, then we merge it with this new fields. 

Alternatively, we can take the base unit and multiply by the precision when doing the actual minting. This'll make sure things are aligned (we should also have sanity checks here), but this may be unexpected behavior from a user's PoV.

**Comment by RajGoodF** [comment] 2024-06-05 06:24
Hi @Roasbeef,

The concept of 'precision' as a key in metadata JSON makes sense. It can be interpreted as standard key in meta information to accurately get where the floating point decimal is to be placed. like if precision is 2 and amount is 12345, then actual decimal is placed at 2 digits to right that is 123.45 on UI. Hence 12345 = 12345 * 10^-2.

Since amount is integer it can not be less then 1, In this one case can be of say precision being 2, then in case if amount is 1, then this will lead to 0.01 on UI. that will be fine. 

So if we are minting 100 USD we will mint 100 * 100 (cents) * 100 (Millicent's) coins on taproot layer. And on taproot layers we will be transferring Millicent's, like one thing now it enables us to transfer as low as 1 Millicent on tapd layer. So for me should I keep precision as '4' when I am creating asset like USD ? So this will give flexibility for user to receive as low as 0.0001 USD at taproot layer and on application layer since our business requirements are not to allow less then 1 cent we need to handle by keeping validation as low as 0.01 USD on app layer itself.

Since Metadata is embedded in asset, and we frequently use RPCs like NewAddr and AddrReceives, can tapd layer internally handle and add one new key in request response so that we don't have to go back and forth of asset and check the actual value to be shown on UI.
 For example when we create address with say 123.45 USD, like can we have another key which can be floating in used rpc calls and internally tapd api handle conversion of floating point numbers to integers based on precision. So basically what I went is while generating address we can just say generate address with 123.45 USD and internally it converts it to 12345 value of asset and get invoice based on 2 precision. Similarly when we receive 12345 on this address it gives another key saying the asset received is 123.45 based on precision. The reason to mention this is that we don't have to lookup asset metadata again and again to get precision value, because at our application layer we will be handling hundreds of asset with different precisions. So lookup every time will create lag at our end. Its just like Msat and Sat in generate just that we are enabling floats here. Like its a weird request but can save us our development efforts.
 
 
 One critical question is since we are minting assets in one group, then is it possible to have different precision for assets in one group, so if by mistake in order to increase supply of USD we mint another asset and then add precision as '6' so it will violate the principle that one asset will have 'precision' as 4 and other as '6' and later when we use RPC calls like generate address based on group key then what precision will be taken, wont it be conflicting.
 
 So most of the properties of asset are actually dependent on group key, I hope we are making this concept clear from our end.
Hence my suggestion since we are moving our apis to group key instead of asset_id should we keep this meta information in group rather then asset.
 
 CC @vanditshah99

**Closed** 2024-06-11 18:51 UTC
