### ISSUE TITLE
transaction rejected: output already spent

### ISSUE THREAD

**Issue by bilthon** [lightninglabs/taproot-assets#332] opened 2023-05-31 16:10 UTC
I'm running `tapd` v0.2.0-alpha on polar and get this error in one instance:

```
2023-05-31 16:05:31.003 [INF] RPCS: Starting RPC Server
2023-05-31 16:05:31.002 [INF] FRTR: Attempting to resume delivery for anchor_txid=22cf1da4f9ace79187227298c490a0b497ed21a2cabebfcedac40b8b5a61b28d
2023-05-31 16:05:31.002 [INF] FRTR: Attempting to resume delivery for anchor_txid=b990385ec0db9375f5fce1ae33052ef414aa1a5429b9becf68d2301a52f49011
2023-05-31 16:05:31.004 [INF] RPCS: RPC server listening on 0.0.0.0:10029
2023-05-31 16:05:31.005 [INF] GRDN: Resuming 0 pending inbound asset events
2023-05-31 16:05:31.006 [INF] GRDN: Loading wallet transactions starting at block height 0
2023-05-31 16:05:31.005 [INF] FRTR: ChainPorter executing state: SendStateBroadcast
2023-05-31 16:05:31.005 [INF] FRTR: ChainPorter executing state: SendStateBroadcast
2023-05-31 16:05:31.006 [INF] CONF: Starting HTTPS REST proxy listener at 0.0.0.0:8089
2023-05-31 16:05:31.008 [INF] RPCS: gRPC proxy started at 0.0.0.0:8089
2023-05-31 16:05:31.009 [INF] SRVR: Taproot Asset Daemon fully active!
2023-05-31 16:05:31.008 [INF] FRTR: Broadcasting new transfer tx, txid=22cf1da4f9ace79187227298c490a0b497ed21a2cabebfcedac40b8b5a61b28d
2023-05-31 16:05:31.008 [INF] GRDN: Checking 5 wallet transactions for inbound assets, this might take a while
2023-05-31 16:05:31.011 [DBG] GRDN: Inspecting tx b990385ec0db9375f5fce1ae33052ef414aa1a5429b9becf68d2301a52f49011 for Taproot Asset address outputs
2023-05-31 16:05:31.009 [INF] FRTR: Broadcasting new transfer tx, txid=b990385ec0db9375f5fce1ae33052ef414aa1a5429b9becf68d2301a52f49011
2023-05-31 16:05:31.013 [DBG] GRDN: Inspecting tx 32073b13a152958b69489f7ea2c9d53a848573ad4c8279c18d6732c5d6fc9926 for Taproot Asset address outputs
2023-05-31 16:05:31.014 [DBG] GRDN: Inspecting tx 6d9becf17713051b5bc6fb0c98931de9786ff3a76e7bf3e6f30a881990065a3f for Taproot Asset address outputs
2023-05-31 16:05:31.015 [DBG] GRDN: Inspecting tx 10f5741e1623d7915538551c083748c66af177a58c0cd72915e3faf967d7d25b for Taproot Asset address outputs
2023-05-31 16:05:31.015 [INF] GRDN: Starting main custodian event loop
2023-05-31 16:05:31.016 [DBG] GRDN: Inspecting tx 22cf1da4f9ace79187227298c490a0b497ed21a2cabebfcedac40b8b5a61b28d for Taproot Asset address outputs
2023-05-31 16:05:31.048 [ERR] FRTR: Error evaluating state (SendStateBroadcast): rpc error: code = Unknown desc = transaction rejected: output already spent
2023-05-31 16:05:31.048 [ERR] SRVR: Shutting down because error in main method: received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-05-31 16:05:31.049 [INF] RPCS: Stopping RPC Server
2023-05-31 16:05:31.050 [INF] SRVR: Shutdown complete

2023-05-31 16:05:31.048 [WRN] FRTR: Unable to advance state machine: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-05-31 16:05:31.050 [WRN] FRTR: No response channel for resumed parcel, not delivering notification
received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
```

I tried re-using a taproot asset address if that's a hint of what might have caused this.

**Comment by bilthon** [comment] 2023-05-31 16:47
This is the sender

**Comment by Roasbeef** [comment] 2023-05-31 18:23
Was this from you trying to do concurrent sends before any prior ones had confirmed? 

Currently the send function isn't safe for concurrent use: https://github.com/lightninglabs/taproot-assets/issues/261

**Comment by bilthon** [comment] 2023-05-31 19:29
No it wasn't concurrent. I tried to re-use an address I've previously successfully used, but that operation was done and I believe the blocks were generated at that point.

**Comment by bilthon** [comment] 2023-06-01 23:35
No, I was using polar, not doing anything fancy, opening a channel would have been something I'd be aware of it doing. The container is still restarting, so I can maybe extract more data if you want. But like I said, all I tried was to re-use an taproot asset address, and I'm pretty sure the previous tx was confirmed.

**Comment by Roasbeef** [comment] 2023-06-02 22:25
When you say taproot address, do you mean a taproot assets address, or regular on chain address? 

> The container is still restarting, so I can maybe extract more data if you want.

It would be super helpful if you can replicate/paste the exact commands you used to trigger the behavior. The error in this case is that an on chain output was double spent.

**Comment by bilthon** [comment] 2023-06-07 21:08
I meat a taproot asset address of course. I did this to test if I could re-use them. And I could not immediately reproduce this, but today I just had it again, this time for an attempt that was made last week and did not immediately cause the issue.

```
2023-06-07 21:03:48.080 [INF] RPCS: Starting RPC Server
2023-06-07 21:03:48.079 [INF] FRTR: Attempting to resume delivery for anchor_txid=82780c8cdf9f6575bd20724ad9f6629fab92f944b698cf7497c394a3c850cd7f
2023-06-07 21:03:48.079 [INF] FRTR: Attempting to resume delivery for anchor_txid=40d84fa210d3215de59f9821fdc73793774fa5c110770386a1fec819a9876a5a
2023-06-07 21:03:48.082 [INF] RPCS: RPC server listening on 0.0.0.0:10029
2023-06-07 21:03:48.082 [INF] GRDN: Resuming 0 pending inbound asset events
2023-06-07 21:03:48.087 [INF] GRDN: Loading wallet transactions starting at block height 0
2023-06-07 21:03:48.082 [INF] FRTR: ChainPorter executing state: SendStateBroadcast
2023-06-07 21:03:48.083 [INF] FRTR: ChainPorter executing state: SendStateBroadcast
2023-06-07 21:03:48.084 [INF] CONF: Starting HTTPS REST proxy listener at 0.0.0.0:8089
2023-06-07 21:03:48.092 [INF] RPCS: gRPC proxy started at 0.0.0.0:8089
2023-06-07 21:03:48.092 [INF] SRVR: Taproot Asset Daemon fully active!
2023-06-07 21:03:48.092 [INF] FRTR: Broadcasting new transfer tx, txid=82780c8cdf9f6575bd20724ad9f6629fab92f944b698cf7497c394a3c850cd7f
2023-06-07 21:03:48.092 [INF] GRDN: Checking 12 wallet transactions for inbound assets, this might take a while
2023-06-07 21:03:48.095 [DBG] GRDN: Inspecting tx 40d84fa210d3215de59f9821fdc73793774fa5c110770386a1fec819a9876a5a for Taproot Asset address outputs
2023-06-07 21:03:48.093 [INF] FRTR: Broadcasting new transfer tx, txid=40d84fa210d3215de59f9821fdc73793774fa5c110770386a1fec819a9876a5a
2023-06-07 21:03:48.096 [DBG] GRDN: Inspecting tx b7f1ffaf1aea3f43712d9df62dd5d92520e31a0057ab889777ffdc43e64c57e8 for Taproot Asset address outputs
2023-06-07 21:03:48.100 [DBG] GRDN: Inspecting tx 3b41536184124daa953f6e42414749379209f303772082c3a5644810c842f059 for Taproot Asset address outputs
2023-06-07 21:03:48.104 [DBG] GRDN: Inspecting tx 87fae0d21cd288afd404f0299169a76d957da75ad861d07df1e5e4703f1d7ca0 for Taproot Asset address outputs
2023-06-07 21:03:48.105 [DBG] GRDN: Inspecting tx ad06246e11af1dd8e958bdf27058cffdaf1deca3366434381d96643b85bd8522 for Taproot Asset address outputs
2023-06-07 21:03:48.106 [DBG] GRDN: Inspecting tx 934d64b8e513fc049e35faf835610e5852453d230969de34d19ee83993469f15 for Taproot Asset address outputs
2023-06-07 21:03:48.106 [DBG] GRDN: Inspecting tx 53816e68ef49f18d46b2fc10add8b56369d024cb67f02e002493cef652b3abf0 for Taproot Asset address outputs
2023-06-07 21:03:48.107 [INF] GRDN: Starting main custodian event loop
2023-06-07 21:03:48.108 [DBG] GRDN: Inspecting tx 82780c8cdf9f6575bd20724ad9f6629fab92f944b698cf7497c394a3c850cd7f for Taproot Asset address outputs
2023-06-07 21:03:48.144 [ERR] FRTR: Error evaluating state (SendStateBroadcast): rpc error: code = Unknown desc = transaction rejected: output already spent
2023-06-07 21:03:48.144 [WRN] FRTR: Unable to advance state machine: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-06-07 21:03:48.144 [ERR] SRVR: Shutting down because error in main method: received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-06-07 21:03:48.145 [INF] RPCS: Stopping RPC Server
2023-06-07 21:03:48.146 [INF] SRVR: Shutdown complete
```

It's not easy to reproduce this, but it doesn't seem to be super rare either. I'm using polar with lnd `v0.16.2-beta` by the way.

**Comment by ffranr** [comment] 2023-06-09 16:32
This is what I think is happening:
1. The send process resumes by re-loading a pending send package.
2. The resumed send package already contains an anchoring tx.
3. The send process resumes by attempting to broadcast the anchoring tx.
4. Since commencing the send event, the anchoring tx has become stale (perhaps LND has used the UTXO?). Therefore, the anchor tx broadcast fails.

If that's the case then completing this issue should make the send process more robust and solve this problem:
https://github.com/lightninglabs/taproot-assets/issues/261

I'll try to see if there's a simpler solution that we can implement in the meantime.

**Comment by ffranr** [comment] 2023-06-09 17:02
The other possibility (which came up in a discussion with @jharveyb ) is that both sending packages are using separate anchoring txs which spend the same UTXO. I think I can create an itest to see if that's possible.

**Comment by ffranr** [comment] 2023-06-12 20:00
( @dstadulis ) I've created this itest to show that the send procedure reserves (duration?) UTXOs even whilst the send process is pending: https://github.com/lightninglabs/taproot-assets/pull/355

**Comment by ffranr** [comment] 2023-06-12 20:34
@jharveyb Good point! Thanks for the clear explination. I've got a test written that's pretty close to what you've described (https://github.com/lightninglabs/taproot-assets/pull/355) I'll investigate!

**Comment by guggero** [comment] 2023-06-13 09:40
Discussed this offline and found two possible scenarios that we want to reproduce:

1. spend same "fee paying" input from lnd:
 - mint asset
 - mine a block
 - consolidate all lnd inputs (sendcoins with sendall true)
 - transfer asset
 - go through all locks/(leases in lnd, unlock all of them
 - transfer second asset
 - see second one fail

2. spend the same asset coin input:
 - mint asset
 - mine a block
 - transfer asset
 - shut down daemon
 - restart daemon, causing the first transfer to be resumed in a separate goroutine
 - do a second transfer which now tries to spend the same asset input

**Comment by ffranr** [comment] 2023-06-14 16:49
JHB shared this comment: https://github.com/lightninglabs/taproot-assets/pull/358#issuecomment-1591331214

> we would want to check for send TX confirmation and jump past re-broadcasting if confirmed

I'm going to open a new PR to do just that.

**Comment by jharveyb** [comment] 2023-06-15 15:49
Scenario 3:

- Mint asset
- Mine a block
- Transfer asset
- Transfer progresses to broadcast
- Shut down `tapd`
- Mine a block, transfer is confirmed
- Restart daemon
- Daemon does not resume parcel correctly, stuck in `SendStateBroadcast`?

**Comment by ffranr** [comment] 2023-06-19 17:18
In addressing this issue we merged this fix: https://github.com/lightninglabs/taproot-assets/pull/358

And also added this integration test: https://github.com/lightninglabs/taproot-assets/pull/365

We think that this issue should be solved, so I'll close this issue.

**Closed by ffranr** 2023-06-19 17:18 UTC
