### ISSUE TITLE
Can import a proof multiple times, creating duplicate asset records

### ISSUE THREAD

**Issue by habibitcoin** [lightninglabs/taproot-assets#258] opened 2023-02-07 23:27 UTC
Using latest lnd and latest on taro

To reproduce:
1. Export a proof via REST
2. Import this proof via REST

You'll now see duplicate asset records created 

![image](https://user-images.githubusercontent.com/114780316/217390009-61cc7d2e-c0d2-4dfe-b3a6-6325494cdc8a.png)

**Comment by habibitcoin** [comment] 2023-02-07 23:29
Also, I always assumed the "amount" field was supposed to be only _my_ current balance of the asset, correct?

I would expect it to be 0 if I import a proof of an asset I do not own

**Comment by Roasbeef** [comment] 2023-05-19 20:18
So what we want to do here is fix the unique constraint on the assets to resolve this. Also if we get a proof import and we can't actually sign with the script key, then we can detect that and not factor it into the balance calls.

**Comment by Roasbeef** [comment] 2023-11-06 20:57
Closing as duplicate of: https://github.com/lightninglabs/taproot-assets/issues/287 

Also the import call rn is considered to be a dev call.

**Closed by Roasbeef** 2023-11-06 20:57 UTC
