### ISSUE TITLE
[bug]: assets with group key don't have asset id displayed after universe bootstrap

### ISSUE THREAD

**Issue by kulisekf** [lightninglabs/taproot-assets#403] opened 2023-07-14 12:26 UTC
When trying to create address for asset using group_key tapcli return error

### Environment
Polar v2.0.0; Docker v20.10.21; Compose v2.13.0 (Win 10) - I also wanted to try it on Ubuntu 20.04 with manual installation of lnd and taproot-assets on testnet, but I didn't want to burden Universe unnecessarily

network setup: 1 Bitcoin Core v25.0; 2 LND v0.16.2-beta; 2 Taproot Assets v0.2.0-alpha

### Steps to reproduce
first i minted the asset:
`tapcli assets mint --type normal --name TestGroup --supply 1000 --meta_bytes "test" --enable_emission true`
`tapcli assets mint finalize`
Quick Mine some block
`tapcli assets mint --type normal --name TestGroup --supply 100 --group_key {tweaked_group_key from previous mint asset}`
`tapcli assets mint finalize`
Quick Mine some block

subsequently on the second Taproot Assets node:
sync universe - I did this using the polar GUI instead of in the terminal (I expect the same result)
using the    `tapcli universe roots`    command I listed assets - there is only one, mined in the previous step
I then tried to create an address using group_key since this asset contains it instead of asset_id
`tapcli addrs new --asset_id edef115aec9971700741c989ac1f781d4649b093b711bbe908018e12b02d8541 --amt 500`

### Actual behavior
[tapcli] unable to make addr: rpc error: code = Unknown desc = unable to make new addr: unable to make address for unknown asset edef115aec9971700741c989ac1f781d4649b093b711bbe908018e12b02d8541: asset group is unknown

Maybe this issue is related to https://github.com/lightninglabs/taproot-assets/issues/299 not sure

**Comment by ffranr** [comment] 2023-07-14 14:59
@kulisekf thanks for starting this issue! I'll take a look at this issue in the next few days.

My initial intuition tells me that it's not related to https://github.com/lightninglabs/taproot-assets/issues/299 , but whatever the cause I think there's certainly room to improve the error message!

**Comment by kulisekf** [comment] 2023-07-14 20:36
Now I'm looking, the group_key value obtained from the universe roots does not match any value from the assets_group section from assets list, while I would expect it to be the same as the tweaked_group_key (this reasoning of mine is based on an experiment in which I created on the node where I mined the assets the address where I put the asset_id of one of those group mints and in the information about the address that is written when creating the address to the console there is a group_key that has the same value as tweaked_group_key)

**Comment by Roasbeef** [comment] 2023-07-14 23:05
> I then tried to create an address using group_key since this asset contains it instead of asset_id
> tapcli addrs new --asset_id edef115aec9971700741c989ac1f781d4649b093b711bbe908018e12b02d8541 --amt 500

So is `edef115aec9971700741c989ac1f781d4649b093b711bbe908018e12b02d8541` the asset ID, or the group key? 

Are you able to repro with the latest version of `tapd`?

**Comment by kulisekf** [comment] 2023-07-15 07:27
@Roasbeef it is group_key. Tried, same result - on my node running Ubuntu 20.04; lncli version 0.16.3-beta; tapcli version 0.2.2-alpha; using tapcli universe roots I listed assets, found asset with group_key and tried to create address - failed

**Comment by jharveyb** [comment] 2023-08-22 16:56
@kulisekf can you try this using the asset ID and not the group key? There is an open spec issue about making address to receive any asset in a group, but for now that should be a specific asset ID.

**Comment by kulisekf** [comment] 2023-08-25 08:55
@jharveyb reproduction procedure - I minted the asset with --enable_emission true, finalized, then the second mint with --group_key, finalized. Now if I use tapcli assets list on the same machine I can create a new address using the asset_id and send to it as well. The problem is that if I wanted to create an address from a different machine than where the mint was performed (or from the same machine, but I'm simulating the process of creating an address from another), I need to perform a universe synchronization and then use the tapcli universe roots command. tapcli universe roots returns me information about group asset, but there is no asset_id anymore, there is only group_key and if I want to create an address using this group_key, it doesn't work, same error. This allows me to send assets created with --enable_emission true only within one machine/instance using asset_id, but can't send them to anyone else because they don't have asset_id

**Comment by jharveyb** [comment] 2023-08-25 16:11
Thank you for the detailed notes! This makes more sense now.

I think we'll need to change the universe sync to also include asset IDs for grouped assets then, along with the pending spec change for addresses to be able to include a group key.

@Roasbeef

**Comment by jharveyb** [comment] 2023-08-29 16:16
Poked around the universe code a bit and we already have the necessary info wrt. asset IDs, IMO it just needs to be shown for assets with a group key. Even after we implement a solution for https://github.com/lightninglabs/taproot-assets/issues/291 , it could still be useful to know which IDs in the group you have synced.

**Comment by guggero** [comment] 2023-09-07 11:50
This will be fixed in https://github.com/lightninglabs/taproot-assets/pull/492.

@kulisekf you cannot use a group key as the asset ID (as those are two distinct identifiers). And currently it's not supported to create an address for a group, rather you have to pick a specific asset ID from the group. To make it easier on the receiver side to find out what asset IDs exist within a group, I've added `amounts_by_asset_id` to the response of `tapcli universe roots`:

Example from regtest:
```
    "universe_roots": {
        "0d2aae2e978544bfaa3f971671b969ed7269d9f152383b049b412429d921ed3a": {
            "id": {
                "group_key": "566269ea1f0a7c7991bb81088948649412fa3f3a44e19f2771db5d858e0225d7"
            },
            "mssmt_root": {
                "root_hash": "dc940b9eb46f30821b791c2a929787eebbdf70eab2eac7e05dff9778ae9a7473",
                "root_sum": "1300"
            },
            "asset_name": "TestGroup",
            "amounts_by_asset_id": {
                "0ed7fdce4dc2f0944eabd70d862856eaeedd9ad8da7f83bb42827e6cb337dbbd": "200",
                "3ec2c5422fe07d4bb80f858ed8611e27510072ca899a69c3059ad743fad4d1a3": "200",
                "9383106e677cbda258be57b47ba35ce45d2d350a17d45ba6a75db2422c9005a0": "100",
                "9748c1785e26d7db5587326e01201045696a311d961b27822c58392008d58a67": "200",
                "ac65bdc60213ec5162c5ec73f38ebdac895ff22848871cec740a2139a9d3c1ca": "200",
                "cbc209697d0830ecf6d8722b968e2c93aeefe885a7fd0bddbadd01b14d202853": "200",
                "ce7c80a8a030b0bc6e3113207b585893bb21698fe3b3c4a391bfb1835101102f": "200"
            }
        }
    }
```

So a valid call to create an address for this example would be:
```
tapcli addrs new --asset_id 9748c1785e26d7db5587326e01201045696a311d961b27822c58392008d58a67 --amt 50
```

**Closed** 2023-09-13 01:16 UTC
Labels: bug, good first issue, v0.3
