### ISSUE TITLE
multi: audit usage of fn.ParSlice

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#527] opened 2023-09-21 23:32 UTC
Today we use `fn.ParSlice` to do parallel operations on a slice. The routine uses an `errgroup` under the covers to handle the concurrency synchronization: https://github.com/lightninglabs/taproot-assets/blob/a201d48152b274e8faec390dab969391171af27e/fn/concurrency.go#L16-L34

Looking at the `godoc` a bit more closely, I realized that:
  * The first goroutine to return an error will cancel the context. 
  * If that context is checked by any of the other goroutines, then they'll all halt and not finish. 

This may have unintended consequences when we want all the goroutines to run to completion. 

We should audit all call sites to make sure that this behavior is acceptable in the scenarios that it's used.

**Comment by dstadulis** [comment] 2023-10-16 15:35
Still needs to be started

**Comment by ffranr** [comment] 2023-10-20 12:06
Uses of `fn.ParSlice`:

1. Used in `MultiArchiver.ImportProofs` to verify a set of proofs. I think this use is correct. We want to fail for all proofs if any proof in the given set fails verification.
2. Used in `ChainPorter.transferReceiverProof` to deliver multiple proofs via proof courier services. I think this use is correct for the moment. If we fail to deliver any one proof then we should re-attempt delivery for all output proofs. I think we currently recognise a send package as complete or not in its entirety.

**Comment by ffranr** [comment] 2023-10-20 12:35
More uses of `fn.ParSlice`:

3. `BatchCaretaker`, state `BatchStateConfirmed`. Function `fn.ParSlice` is used twice in the `BatchStateConfirmed` state. Both cases involve submitting proofs individually for storage via `ProofFiles.ImportProofs`. If one of the parallel attempts fail then `fn.ParSlice` would cancel the remaining parallel instances. However, some instances may have succeeded. IMO, we should get rid of `fn.ParSlice` in both of these cases and submit proofs atomically to `ProofFiles.ImportProofs`.
4. There are two uses in `FederationEnvoy`. One for syncing across servers and another for syncing across proofs for a given server. In both cases we currently avoid returning an error from the callbacks passed into `fn.ParSlice`. These instances should work as they are. However, we should probably create a new parallelization function that doesn't quit all instances on error as a more appropriate version of `fn.ParSlice`.
5. `MintingArchive.RegisterNewIssuanceBatch` used in verifying batch proofs. This use is correct. We want to quite verification if we fail to verify any proof in the batch.
6. `SimpleSyncer`, used to sync universes. Three different uses. These uses don't really matter because `FederationEnvoy` correctly handles errors in `fn.ParSlice` callbacks. However, `SimpleSyncer` would be more robust if it didn't use `fn.ParSlice`.

**Comment by ffranr** [comment] 2023-10-20 12:39
Those 6 points cover all `fn.ParSlice` call sites. I'll create separate issues to follow up with point 3 and point 6.

I'm going to add my self to the assignees of this issue and then move it into state "In Review".

**Comment by dstadulis** [comment] 2023-11-02 18:17
update from @ffranr:
This issue is complete from my POV. @jharveyb will review to double check @ffranr reasoning

**Comment by jharveyb** [comment] 2023-11-02 21:16
We're up to 11 uses now, verified the previous ones and new ones, and agree with the conclusions.

Agree that we want a non-erring worker pool func, as right now for some the sync usage we work around `ParSlice` by just not propogating errors from workers and logging instead. I think ideally we'd returned all worker errors but not cancel workers upon err.

**Closed** 2023-11-02 21:19 UTC
Labels: bug
