### ISSUE TITLE
transaction rejected: output already spent

### ISSUE THREAD

**Issue by snow884** [lightninglabs/taproot-assets#384] opened 2023-07-05 18:32 UTC
When trying to execute a transaction my tapd deamon crashes with a message

```
received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
```

Here is the follow log

```
023-07-03 22:44:45.129 [INF] PROF: Waiting (6h0m0s) for receiver ACK via sid=47cb8a087eb0e675c5459db99032bbfca931f935e88e3f49e8eba1aa6eb8295cf2116579321d8aa885e59105e06bc340ef61eae83f5dd9f78b4b7fe97f2a7484
2023-07-03 22:44:58.185 [INF] FRTR: Received to send request to 1 addrs: [TapAddr{id=312f607c79447cdb6f951bc490b41e6d4807e089e130830ac1a5c5b31af83c7f, amount=1, script_key=02561b7c748de7fadaf240126b381c39e0c765b868b359e6ddbedce265f2f120e7}]
2023-07-03 22:44:58.185 [INF] FRTR: ChainPorter executing state: SendStateVirtualCommitmentSelect
2023-07-03 22:44:58.215 [INF] FRTR: Identified 1 eligible asset inputs for send of 1 to 312f607c79447cdb6f951bc490b41e6d4807e089e130830ac1a5c5b31af83c7f
2023-07-03 22:44:58.216 [INF] FRTR: Selected 1 asset inputs for send of 1 to 312f607c79447cdb6f951bc490b41e6d4807e089e130830ac1a5c5b31af83c7f
2023-07-03 22:44:58.220 [DBG] TAPD: Deriving new key for fam_family=212
2023-07-03 22:44:58.225 [DBG] TAPD: Deriving new key for fam_family=212
2023-07-03 22:44:58.231 [INF] FRTR: ChainPorter executing state: SendStateVirtualSign
2023-07-03 22:44:58.231 [INF] FRTR: Generating Taproot Asset witnesses for send to: 02561b7c748de7fadaf240126b381c39e0c765b868b359e6ddbedce265f2f120e7
2023-07-03 22:44:58.235 [INF] FRTR: ChainPorter executing state: SendStateAnchorSign
2023-07-03 22:44:58.238 [INF] FRTR: Constructing new Taproot Asset commitments for send to: 02561b7c748de7fadaf240126b381c39e0c765b868b359e6ddbedce265f2f120e7
2023-07-03 22:44:58.255 [INF] FRTR: Received funded PSBT packet
2023-07-03 22:44:58.255 [INF] FRTR: Adjusting send pkt by delta of 59 from 198 sats to 257 sats
2023-07-03 22:44:58.255 [DBG] FRTR: Signing PSBT
2023-07-03 22:44:58.258 [DBG] FRTR: Got signed PSBT
2023-07-03 22:44:58.258 [INF] FRTR: ChainPorter executing state: SendStateLogCommit
2023-07-03 22:44:58.273 [INF] FRTR: Committing pending parcel to disk
2023-07-03 22:44:58.280 [INF] FRTR: ChainPorter executing state: SendStateBroadcast
2023-07-03 22:44:58.283 [INF] FRTR: Broadcasting new transfer tx, txid=b71ecd4b19248f702cc3dc2f337c2f09dcfd398b30d4983eaa2758c040ddd1d0
2023-07-03 22:44:58.290 [DBG] GRDN: Inspecting tx b71ecd4b19248f702cc3dc2f337c2f09dcfd398b30d4983eaa2758c040ddd1d0 for Taproot Asset address outputs
2023-07-03 22:44:58.298 [ERR] FRTR: Error evaluating state (SendStateBroadcast): rpc error: code = Unknown desc = transaction rejected: output already spent
2023-07-03 22:44:58.298 [WRN] FRTR: Unable to advance state machine: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-07-03 22:44:58.298 [ERR] RPCS: [/taprpc.TaprootAssets/SendAsset]: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-07-03 22:44:58.299 [ERR] SRVR: Shutting down because error in main method: received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
2023-07-03 22:44:58.299 [INF] RPCS: Stopping RPC Server
2023-07-03 22:44:58.304 [INF] SRVR: Shutdown complete

received critical error from subsystem: rpc error: code = Unknown desc = transaction rejected: output already spent
```

**Comment by dstadulis** [comment] 2023-07-05 18:48
hey @snow884 

Wondering if you're encountering an issue #332 which might have been fixed #358 and #365

A response with your environment will help identify if the issue may still be reoccurring 

```sh
tapcli getinfo                                    # version of `tapd`, `lnd`, and network
uname -mrsv                                          # operating system 
bitcoind --version || btcd --version # version of `btcd`, `bitcoind`, or other backend
```

**Comment by guggero** [comment] 2023-07-10 11:24
Are you running 0.2.2 and did you start from scratch (removing the whole `.tadp` directory after upgrading to 0.2 or 0.2.2)?

**Comment by dstadulis** [comment] 2023-07-25 18:52
@snow884 can you confirm you no longer encounter this?

**Comment by guggero** [comment] 2023-08-08 18:01
Closing as duplicate of #261 (will be fixed by that).

**Closed by guggero** 2023-08-08 18:01 UTC
