### ISSUE TITLE
bip-taro: implement provable burning and verification

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#24] opened 2022-04-19 22:37 UTC
One important feature is the ability to _burn_ assets, and also prove to third parties that those assets have been burnt. 

This addition is defined currently in this PR to my BIP repo: https://github.com/Roasbeef/bips/pull/21. 

At a high level, we'll use a series of non-inclusion proofs, both within the tapscript level and also across the other outputs in the transaction. 

This is related to https://github.com/lightninglabs/taro/issues/20 as the set of non-inclusion proofs outlined there will be used to ensure the asset commitment doesn't persist. 

# Steps To Completion
- [ ] Implement a routine that burns an asset by removing the commitment from the asset tree.
- [ ] Implement a routine related to the above that generates a non-inclusion proof on the taproot-asset level proving the asset is no longer committed to. 
- [ ] Use the above, along side #20 to implement the final component which is to prove that no other commitments are valid in the transaction. Assuming widespread BIP 86 usage is a safe assumption.
- [ ] Update taproot-asset BIPs to reflect protocol requirements for provable burning.

**Comment by jharveyb** [comment] 2023-06-06 15:28
After some offline discussion with @guggero, I think we've narrowed down the options here. Generally, we're aware of two approaches:

- Burn via proof-of-omission. Instead if re-anchoring an asset into the next anchor output, or spending it, omit the asset from the tap tree. This allows for a proof-of-exclusion to serve as a proof-of-burn.

- - Drawback: May collide with future protocol changes to allow for asset 'teleporting' via ANYPREVOUT-like mechanics, that could replace asset reanchoring with new signatures. I think we could mitigate that possible collision by requiring a more strict asset state before omission, like using a specific sighash.


- Burn via a provaly unspendable script key, followed by omission. The proof for the next spend of the asset includes a field in the associated proof that provides the data needed to verify that the current script key is unspendable / unsatisfiable. The asset is then never moved again, and therefore omitted from future spends of the anchor output.

- - This option ***cannot*** use a shared NUMS key, since that would cause burnt assets to collide in the tap tree if transfers are batched in a pocket universe, or other transfer batching scheme (the tree requires tap asset script keys to be unique).

- - Instead, we can use a uniquely unspendable tweaked script key for the asset. One option may be to use the shared NUMS key used for split asset tombstoning as the internal key, and use a unique unspendable tap script for the tweak. If we use the current asset position in the tap tree as input to generate that tap script (which is already unique to this anchor output), that should provide a sufficiently random tweaked script key.

- - - One example of such an unspendable tap script:
```golang
func deriveBurnKey(asset Asset, outpoint Outpoint) PublicKey {

// Use the path of the asset in the tap tree as a unique hash preimage.
burnPreimage := []byte{outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey()}

// Use OP_RETURN to make the script unspendable.
var burnScript *ScriptBuilder
burnScript.AddOp(OP_RETURN)
burnScript.AddData(Hash160(burnPreimage))

// Build a tapscript tree from the script and tweak the NUMS key.
burnTapscriptLeaf := NewBaseTapLeaf(burnScript)
burnTapscriptTree := AssembleTaprootScriptTree(burnTapscriptLeaf)
burnTapscriptTreeRoot := burnTapscriptTree.RootNode.TapHash()
burnScriptKey := ComputeTaprootOutputKey(NUMSPubkey, burnTapscriptTreeRoot)

}
```

- - Any verifier can recompute the asset script key if the asset proof includes a flag that the asset is unspendable. On the next spend of the anchor output, the asset can be omitted from the tap tree, and the proof chain for the asset would end at the previous transaction.

One consideration is allowing Universe servers to track the total balance burned for an asset; both of these burn options would allow for that without much overhead.

@Roasbeef thoughts?

**Comment by Roasbeef** [comment] 2023-06-07 00:41
> Burn via proof-of-omission. Instead if re-anchoring an asset into the next anchor output, or spending it, omit the asset from the tap tree. This allows for a proof-of-exclusion to serve as a proof-of-burn.
> Drawback: May collide with future protocol changes to allow for asset 'teleporting' via ANYPREVOUT-like

Do you have a concrete conflict here, or is this statement more speculative? In the case of using something noinput-like to not have to add additional signatures for anchored assets, I don't see how that's incompatible with certain assets jut not existing in the next tree. 

One other potential drawback (compared to other alternatives) is that proving this requires state N and also state N+1 proofs to show the asset was omitted. This is actually very similar to the ideas re unilateral exit from a Pocket Universe by proving that the Universe operator effectively _burned_ your assets. 

> Burn via a provaly unspendable script key, followed by omission.

Related to the above: I don't see why omission here is acceptable, but someone incompatible re the above if we just omit all together. 

I think one other advantage of sending to a NUMS key is that you only need that single state transition to prove the asset has been burned. One disadvantage here may be that it effectively takes _two steps_ to complete a burn. This might end up requiring a bit more state and a dedicated sub-system to do in a foolproof manner. 

Zooming out, I think the idea of deriving a unique burn key from the existing NUMS key and a unique path for the leaf works as well.

**Comment by guggero** [comment] 2023-08-22 12:26
Re-capping my current understanding of how we want to proceed (please correct me if incorrect).

The flow for burning would look something like this:
 - 500 units of asset A are minted or received in on-chain TX `tx_0`, outpoint `tx_0:0`.
 - User wants to burn 300 units of that asset, calls `BurnAssets(A, 300)` which creates a vPSBT with two outputs (internal split), with 200 units going back to a fresh valid script key and 300 units going to the specially constructed NUMS key, using `outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey()` as the preimage, where `outpoint` is `tx_0:0`. This is a 1-in-1-out BTC anchor TX in terms of asset commitments (ignoring any fee sponsoring inputs and bip86 outputs).
 - The proof for the virtual output 0 (200 units of change) is a normal transfer proof
 - The proof for the virtual output 1 (300 units to burn) is a transfer proof with the new `burn_reveal` field set, that reveals `outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey()`.
 - Both these assets are re-created in the DB as asset leaves, but the burned one with the new DB field `is_burned` being set to `true` (probably makes sense to also set the `is_spent` to true as well, since you can't spend a burned asset).
 - During coin selection, any assets that have `is_burned` (or `is_spent`) for that matter are filtered out and are not included in the next tree (the same way we today filter out any 0-value tombstones)

This leaves us with the following questions to answer before coding can begin:
 - What happens if the burn amount is greater than a single asset UTXO we have available? Let's say we want to burn 800 units but only have an asset UTXO of 400 and another of 600 units. Do we need to create two virtual burn outputs, one for each UTXO outpoint we're spending? I would assume yes. So we'd burn 400 units of the first UTXO and 200 units of the second one, giving us 200 in change.
 - Do we need to be able to combine burns and regular sends into a single on-chain transaction? Or is it okay for now if the burn process just leases/locks/reserves the UTXOs and only makes the change available for further sends once it is confirmed? cc @dstadulis 
 - Do we really need another layer of reveal with hashing the preimage in the `OP_RETURN`? Or would it be enough to simply put the `outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey()` data in there directly? Since we already reveal the `OP_RETURN` script leaf in the burn proof/reveal, I don't think we need another layer of indirection.

**Comment by jharveyb** [comment] 2023-08-22 18:34
This matches my understanding - I don't think the transfer proof actually needs to reveal anything on burn though? And `burn_reveal` can just be a bool. The receiver can recompute the `TapCommitmentKey()` and `AssetCommitmentKey()`, and the outpoint is already in the proof elsewhere.

We probably also want to update some RPC filters to exclude burnt assets from sum amounts.

W.r.t. your three points:

 - I think this would be easiest as an asset UTXO merge + burn the merged amount? So:
 - - Input: 400, 600, Output: 800 (burnt), 200
 - I think we technically support merging UTXOs right now but I can't think of tests for it.
 
  - I assume we want the first?
  
  - Good point, I guess we don't need to actually hash there.

**Comment by Roasbeef** [comment] 2023-08-22 19:21
May also make sense to have an RPC to show the total set of burned UTXOs for a given asset.

**Comment by guggero** [comment] 2023-08-22 19:35
> I don't think the transfer proof actually needs to reveal anything on burn though?

Ah, right, that makes sense. But then it needs to be clear what t`outpoint` was actually being referred to, which kind of is what my other question tried to get at.

>  I think this would be easiest as an asset UTXO merge + burn the merged amount?

But then the `outpoint` in the burn proof would refer to the new state transaction's anchor output where the burn resides in? Otherwise, _which_ input outpoint would you use if you merge multiple inputs?

> I think we technically support merging UTXOs right now but I can't think of tests for it.

IIRC we removed some of the checks and added an integration test, but not a very extensive suite of tests yet. There are probably some TODOs left in there.

> Good point, I guess we don't need to actually hash there.

Cool, so the updated (pseudo) code would look like this:

```golang
func deriveBurnKey(asset Asset, outpoint Outpoint) PublicKey {

// Use the path of the asset in the tap tree to get a unique tweak for the script key.
burnData := []byte{outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey()}

// Use OP_RETURN to make the script unspendable.
var burnScript *ScriptBuilder
burnScript.AddOp(OP_RETURN)
burnScript.AddData(burnData)

// Build a tapscript tree from the script and tweak the NUMS key.
burnTapscriptLeaf := NewBaseTapLeaf(burnScript)
burnTapscriptTree := AssembleTaprootScriptTree(burnTapscriptLeaf)
burnTapscriptTreeRoot := burnTapscriptTree.RootNode.TapHash()
burnScriptKey := ComputeTaprootOutputKey(NUMSPubkey, burnTapscriptTreeRoot)

}
```

**Comment by Roasbeef** [comment] 2023-08-22 23:15
> The proof for the virtual output 1 (300 units to burn) is a transfer proof with the new burn_reveal field set, that reveals outpoint, asset.TapCommitmentKey(), asset.AssetCommitmentKey().


Why do we need a new field for the burn reveal? Isn't it enough that it's sent to a NUMs point? If we want to ensure it's unique each time, then I think the "publicly available" information could be used for derivation (eg: asset ID and the prev input outpoint or something). 

> What happens if the burn amount is greater than a single asset UTXO we have available? Let's say we want to burn 800 units but only have an asset UTXO of 400 and another of 600 units.

I think the user either consolidates first. Or we have two outputs that are burnt as you mention. 

> Do we need to be able to combine burns and regular sends into a single on-chain transaction?

I think base version it can be distinct (to minimize scope). In the future, we want to implement optimistic aggregation for sends, and a burn is a special type of send, so it would be folded in. 

> Do we really need another layer of reveal with hashing the preimage in the OP_RETURN? 

Sounds overly complicated? Maybe I need to revisit the entire transcript, the simplest thing IIUC would just be to either re-use the same NUMs key for burning, or make one that's derived from the asset "position" information.

**Comment by guggero** [comment] 2023-08-23 08:54
> Isn't it enough that it's sent to a NUMs point?

Yes, but we need a unique NUMS point for each burn. See https://github.com/lightninglabs/taproot-assets/issues/24#issuecomment-1578985230, mainly this comment:

> This option cannot use a shared NUMS key, since that would cause burnt assets to collide in the tap tree if transfers are batched in a pocket universe, or other transfer batching scheme (the tree requires tap asset script keys to be unique).

That's why we add the unique information as an `OP_RETURN` in the script tree in order to tweak the static NUMS key which becomes the internal key. But because now every burn key is different, we need some kind of flag on the proof to mark it as a burn script key.

**Comment by jharveyb** [comment] 2023-08-23 15:44
> But then the `outpoint` in the burn proof would refer to the new state transaction's anchor output where the burn resides in? Otherwise, _which_ input outpoint would you use if you merge multiple inputs?

True, after looking at the scheme again I think merging wouldn't work. I think the solution is as you mentioned, to have some simple 'coin selection' for burning to determine which amounts from which inputs are burnt.

> Cool, so the updated (pseudo) code would look like this:

Yes, this looks correct.

> I think base version it can be distinct (to minimize scope). In the future, we want to implement optimistic aggregation for sends, and a burn is a special type of send, so it would be folded in.

I agree - I think eventually we could have some non-address request accepted by the transfer call to request a burn instead of a send, but def not worth worrying about right now.

> Sounds overly complicated? Maybe I need to revisit the entire transcript, the simplest thing IIUC would just be to either re-use the same NUMs key for burning, or make one that's derived from the asset "position" information.

Deriving for asset 'position' information is basically the currently outlined scheme. Without the flag, we can't know which assets we should validate a burn for. Once we know which assets were supposed to use a burning script key, the proof object already has all the data necessary to validate the burn itself.

Wrt. implications for universes and user-facing display, I think the accounting for burnt balances can be handled client-side vs. modifying the actual tree layout. I'm mostly concerned with not changing the invariants we have right now for the root sums of these trees.

E.x., a user burns some assets and sends these proofs to a universe server. The proof objects for the burnt assets have the `burnt` flag set. The user's `tapd` has a separate field in the `balances` call for burnt assets. The universe server validates the burn, and includes a `burnt` flag when serving the proofs for these assets to users.

I think overall the universe and RPC changes are separate issues from just the spec definition of an asset burn.

**Comment by jharveyb** [comment] 2023-08-24 15:34
After further offline discussion, I think this is actually the best way to make the unspendable key:

https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#cite_note-23

Where instead of using an unspendable script, we use the unique NUMS key as an invalid tapscript root. I don't think there's a need to reinvent unspendable taproot keys for this use case.

**Comment by Roasbeef** [comment] 2023-08-24 18:43
> Without the flag, we can't know which assets we should validate a burn for. Once we know which assets were supposed to use a burning script key, the proof object already has all the data necessary to validate the burn itself.

I guess in my mind a burn is no different from a normal state transition. It's spent to some output key, we don't usually do any verification on the output keys though. However, given the deterministic information, which we can use to derive what the burn key _would_ be, we can recognize it as a burn. You would never see a burn when verifying your own asset history, or the history of a "live" asset. 

> Where instead of using an unspendable script, we use the unique NUMS key as an invalid tapscript root.


Yeah this is what I'm advocating for. You can verify the base NUMs key we use (re-derive it). You can also verify that a key is the result of some information used to tweak the NUMs key. We can go farther and make the NUMs key into a BIP86 key if we want (provably no script path). 

No strong feelings on the burn flag/bit or not. Can see how it can be useful for a dedicated RPC.

**Comment by jharveyb** [comment] 2023-08-24 18:52
Mm I think you'd want to track a balance you burnt at a minimum; I can see how you'd do that without actually flagging it in the proof and just flag it locally.

I think it's also a follow-up question that could become clearer once work on this starts tbh, I'm also not married to any particular method for tracking the burnt balance.

**Closed** 2023-09-19 02:20 UTC
Labels: assets, burning, v0.3
